apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: paystream
  labels:
    app: webhook-service
    app.kubernetes.io/part-of: paystream
spec:
  selector:
    app: webhook-service
  ports:
    - name: http
      port: 8087
      targetPort: 8087
  type: ClusterIP
