apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: paystream
  labels:
    app: auth-service
    app.kubernetes.io/part-of: paystream
spec:
  selector:
    app: auth-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
