apiVersion: v1
kind: Service
metadata:
  name: audit-service
  namespace: paystream
  labels:
    app: audit-service
    app.kubernetes.io/part-of: paystream
spec:
  selector:
    app: audit-service
  ports:
    - name: http
      port: 8089
      targetPort: 8089
  type: ClusterIP
