apiVersion: v1
kind: Service
metadata:
  name: wallet-service
  namespace: paystream
  labels:
    app: wallet-service
    app.kubernetes.io/part-of: paystream
spec:
  selector:
    app: wallet-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
  type: ClusterIP
