spring:
  application:
    name: paystream-eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    # This node is the server — it does not register itself or fetch peers
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # Disable strict peer-to-peer replication in local dev (single node)
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
